//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
// 
namespace BookViewerApp.Storages.WindowStates {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/WindowStates.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/WindowStates.xsd", IsNullable=false)]
    public partial class WindowStates : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WindowStatesLast lastField;
        
        private WindowStatesEntry[] entriesField;
        
        /// <remarks/>
        public WindowStatesLast Last {
            get {
                return this.lastField;
            }
            set {
                this.lastField = value;
                this.RaisePropertyChanged("Last");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Entry", IsNullable=false)]
        public WindowStatesEntry[] Entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
                this.RaisePropertyChanged("Entries");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/WindowStates.xsd")]
    public partial class WindowStatesLast : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WindowState windowStateField;
        
        /// <remarks/>
        public WindowState WindowState {
            get {
                return this.windowStateField;
            }
            set {
                this.windowStateField = value;
                this.RaisePropertyChanged("WindowState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/WindowStates.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/WindowStates.xsd", IsNullable=false)]
    public partial class WindowState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[][] windowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ExplorerTab", typeof(WindowStateWindowExplorerTab), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ViewerTab", typeof(WindowStateWindowViewerTab), IsNullable=false)]
        public object[][] Window {
            get {
                return this.windowField;
            }
            set {
                this.windowField = value;
                this.RaisePropertyChanged("Window");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/WindowStates.xsd")]
    public partial class WindowStateWindowExplorerTab : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string srcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
                this.RaisePropertyChanged("src");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/WindowStates.xsd")]
    public partial class WindowStateWindowViewerTab : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string tokenField;
        
        private string pathField;
        
        private string pathRelativeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PathRelative {
            get {
                return this.pathRelativeField;
            }
            set {
                this.pathRelativeField = value;
                this.RaisePropertyChanged("PathRelative");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/WindowStates.xsd")]
    public partial class WindowStatesEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private WindowState windowStateField;
        
        private string titleField;
        
        private System.DateTime originField;
        
        private bool originFieldSpecified;
        
        private System.DateTime updatedField;
        
        private bool updatedFieldSpecified;
        
        /// <remarks/>
        public WindowState WindowState {
            get {
                return this.windowStateField;
            }
            set {
                this.windowStateField = value;
                this.RaisePropertyChanged("WindowState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
                this.RaisePropertyChanged("origin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originSpecified {
            get {
                return this.originFieldSpecified;
            }
            set {
                this.originFieldSpecified = value;
                this.RaisePropertyChanged("originSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
                this.RaisePropertyChanged("updated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatedSpecified {
            get {
                return this.updatedFieldSpecified;
            }
            set {
                this.updatedFieldSpecified = value;
                this.RaisePropertyChanged("updatedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
