/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DirectoryInfoAndSomeAdditionalDataLikeCurrentDirectory {
    currentDirectory?: string;
    previewFile?: string;
    rootName?: string;
    basePath?: string;
    pageDirection?: "left" | "right" | "down";
    entries?: {
        folder?: string;
        name?: string;
        isFolder?: boolean;
        size?: number;
        updated?: string;
        [k: string]: unknown;
    }[];
    [k: string]: unknown;
}
