using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.ComponentModel;
using System.Collections;
using System.Collections.ObjectModel;

using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Media.Imaging;
using Windows.UI.Xaml.Data;

namespace BookViewerApp.ViewModels
{
    public class BookViewModel : INotifyPropertyChanged
    {
        public BookViewModel()
        {
            this.PropertyChanged += (s, e) =>
            {
                PageVisualAddCommand.OnCanExecuteChanged();
                PageVisualSetCommand.OnCanExecuteChanged();
                PageVisualMaxCommand.OnCanExecuteChanged();
            };
        }

        private Commands.ICommandEventRaiseable _PageVisualAddCommand;
        private Commands.ICommandEventRaiseable _PageVisualSetCommand;
        private Commands.ICommandEventRaiseable _PageVisualMaxCommand;
        private Commands.ICommandEventRaiseable _SwapReverseCommand;
        private Commands.ICommandEventRaiseable _AddCurrentPageToBookmarkCommand;

        private System.Windows.Input.ICommand _GoNextBookCommand;
        private System.Windows.Input.ICommand _GoPreviousBookCommand;

        public Commands.ICommandEventRaiseable PageVisualAddCommand { get {return _PageVisualAddCommand = _PageVisualAddCommand?? new Commands.PageVisualAddCommand(this); } }
        public Commands.ICommandEventRaiseable PageVisualSetCommand { get { return _PageVisualSetCommand = _PageVisualSetCommand ?? new Commands.PageVisualSetCommand(this); } }
        public Commands.ICommandEventRaiseable PageVisualMaxCommand { get { return _PageVisualMaxCommand = _PageVisualMaxCommand ?? new Commands.PageVisualMaxCommand(this); } }
        public Commands.ICommandEventRaiseable SwapReverseCommand { get { return _SwapReverseCommand = _SwapReverseCommand ?? new Commands.CommandBase((a)=> { return true; },(a)=> { this.Reversed = !this.Reversed; }); } }
        public Commands.ICommandEventRaiseable AddCurrentPageToBookmarkCommand { get { return _AddCurrentPageToBookmarkCommand = _AddCurrentPageToBookmarkCommand ?? new Commands.AddCurrentPageToBookmark(this); } }
        public System.Windows.Input.ICommand GoNextBookCommand { get { return _GoNextBookCommand = _GoNextBookCommand ?? new Commands.AddNumberToSelectedBook(this, 1); } }
        public System.Windows.Input.ICommand GoPreviousBookCommand { get { return _GoPreviousBookCommand = _GoPreviousBookCommand ?? new Commands.AddNumberToSelectedBook(this, -1); } }

        public string Title { get { return _Title; } set { _Title = value; OnPropertyChanged(nameof(Title)); } }
        public string _Title = "";

        public async void Initialize(Windows.Storage.IStorageFile value, Control target = null)
        {
            this.Loading = true;
            var book = await Books.BookManager.GetBookFromFile(value);
            if (book != null && book is Books.IBookFixed)
            {
                Initialize(book as Books.IBookFixed, target);
                this.Title = System.IO.Path.GetFileNameWithoutExtension(value.Name);
            }
            this.Loading = false;
        }

        public async void Initialize(Books.IBookFixed value, Control target=null)
        {
            this.Loading = true;
            if (BookInfo != null) SaveInfo();
            this.Title = "";

            var pages = new ObservableCollection<PageViewModel>();
            var option = OptionCache = target == null ? OptionCache : new Books.PageOptionsControl(target);
            for (uint i = 0; i < value.PageCount; i++)
            {
                uint page = i;
                pages.Add(new PageViewModel(new Books.VirtualPage(() => { var p = value.GetPage(page); p.Option = option; return p; })));
            }
            this._Reversed = false;
            this._PageSelected = 0;
            ID = value.ID;
            this.Pages = pages;
            BookInfo = await BookInfoStorage.GetBookInfoByIDOrCreateAsync(value.ID);
            var tempPageSelected = (bool)SettingStorage.GetValue("SaveLastReadPage") ? (int)(BookInfo?.GetLastReadPage()?.Page ?? 1):1;
            this.PageSelectedDisplay = tempPageSelected == this.PagesCount ? 1 : tempPageSelected;
            this.Reversed = BookInfo?.PageReversed ?? false;
            OnPropertyChanged(nameof(Reversed));
            this.AsBookShelfBook = null;

            this.Bookmarks = new ObservableCollection<BookmarkViewModel>();
            {
                var rl = new Windows.ApplicationModel.Resources.ResourceLoader();
                var bm = new BookmarkViewModel() { Page = 1, AutoGenerated = true, Title = rl.GetString("BookmarkTop/Title") };
                this.Bookmarks.Add(bm);
            }
            foreach (var bm in BookInfo.Bookmarks)
            {
                this.Bookmarks.Add(new BookmarkViewModel(bm) );
            }
            {
                var rl = new Windows.ApplicationModel.Resources.ResourceLoader();
                var bm = new BookmarkViewModel() { Page = this.PagesCount, AutoGenerated = true, Title = rl.GetString("BookmarkLast/Title") };
                this.Bookmarks.Add(bm);
            }
            this.Loading = false;
        }

        private Books.PageOptionsControl OptionCache;

        public BookShelfViewModels.BookShelfBookViewModel AsBookShelfBook { get { return _AsBookShelfBook; } set { _AsBookShelfBook = value;OnPropertyChanged(nameof(AsBookShelfBook)); } }
        private BookShelfViewModels.BookShelfBookViewModel _AsBookShelfBook;

        public bool Loading { get { return _Loading; } set { _Loading = value; OnPropertyChanged(nameof(Loading)); } }
        private bool _Loading = true;

        private BookInfoStorage.BookInfo BookInfo=null;
        public void SaveInfo()
        {
            if (BookInfo == null) return;
            BookInfo.Bookmarks.Clear();
            BookInfo.SetLastReadPage((uint)this.PageSelectedDisplay);
            foreach (var bm in this.Bookmarks)
            {
                if (!bm.AutoGenerated)
                    BookInfo.Bookmarks.Add(new BookInfoStorage.BookInfo.BookmarkItem() { Page = (uint)bm.Page, Title = bm.Title, Type = BookInfoStorage.BookInfo.BookmarkItem.BookmarkItemType.UserDefined });
            }
            BookInfo.PageReversed = this.Reversed;
        }

        public string ID { get { return _ID; } private set { _ID = value;OnPropertyChanged(nameof(ID)); } }
        private string _ID;

        public event PropertyChangedEventHandler PropertyChanged;
        private void OnPropertyChanged(string name)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }

        public int PageSelected
        {
            get { return _PageSelected; }
            set
            {
                if (value - 1 > PagesCount) return;
                if (value < 0) _PageSelected = 0;
                else _PageSelected = value;
                OnPropertyChanged(nameof(PageSelectedDisplay));
                OnPropertyChanged(nameof(PageSelectedVisual));
                OnPropertyChanged(nameof(ReadRate));
                OnPropertyChanged(nameof(CurrentBookmarkName));
                OnPropertyChanged(nameof(PageSelected));
            }
        }

        public int PageSelectedDisplay
        {
            get { return _PageSelected+1; }
            set
            {
                PageSelected = value - 1;
            }
        }
        private int _PageSelected = -1;

        public int PageSelectedVisual
        {
            get { return Reversed ? Math.Max(PagesCount - PageSelectedDisplay, 0) : _PageSelected; }
            set
            {
                PageSelectedDisplay = Reversed ? PagesCount - value : value + 1;
            }
        }

        public ObservableCollection<PageViewModel> Pages
        {
            get { return _Pages; }
            set { _Pages = value;OnPropertyChanged(nameof(Pages));OnPropertyChanged(nameof(PagesCount)); OnPropertyChanged(nameof(ReadRate)); }
        }
        private ObservableCollection<PageViewModel> _Pages = new ObservableCollection<PageViewModel>();

        public int PagesCount { get { return _Pages.Count(); } }

        public double ReadRate
        {
            get { return Math.Min((double)PageSelectedDisplay / Pages.Count(),1.0); }
            set { PageSelectedDisplay = (int)(value * Pages.Count);  OnPropertyChanged(nameof(ReadRate)); }
        }

        public string CurrentBookmarkName { get
            {
                foreach (var bm in this.Bookmarks)
                {
                    if (bm.Page == this.PageSelectedDisplay && bm.AutoGenerated == false)
                    {
                        return bm.Title;
                    }
                }
                return "";
            }
            set
            {
                foreach (var bm in this.Bookmarks)
                {
                    if (bm.Page == this.PageSelectedDisplay && bm.AutoGenerated == false)
                    {
                        if (string.IsNullOrEmpty(value))
                        {
                            this.Bookmarks.Remove(bm);
                            goto BookmarkUpdate;
                        }
                        else {
                            bm.Title = value;
                            goto BookmarkUpdate;
                        }
                    }
                }
                if (string.IsNullOrEmpty(value)) return;
                this.Bookmarks.Add(new BookmarkViewModel() { AutoGenerated = false, Page = this.PageSelectedDisplay, Title = value });
                BookmarksSort();

                BookmarkUpdate:
                OnPropertyChanged(nameof(CurrentBookmarkName));
                OnPropertyChanged(nameof(Bookmarks));
            }
        }

        public bool Reversed
        {
            get { return _Reversed; }
            set
            {
                if (Reversed != value)
                {
                    _Reversed = value;
                    OnPropertyChanged(nameof(Reversed));
                }
            }

        }
        private bool _Reversed = false;

        public ObservableCollection<BookmarkViewModel> Bookmarks
        {
            get { return _Bookmarks; }
            set { _Bookmarks = value; BookmarksSort(); OnPropertyChanged(nameof(Bookmarks)); OnPropertyChanged(nameof(CurrentBookmarkName));  }
        }
        private ObservableCollection<BookmarkViewModel> _Bookmarks = new ObservableCollection<BookmarkViewModel>();

        private void BookmarksSort()
        {
            _Bookmarks = new ObservableCollection<BookmarkViewModel>(_Bookmarks.ToList().OrderBy((a) => { return a.AutoGenerated ? -1 : a.Page; }));
        }
    }

    public class PageViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        private void OnPropertyChanged(string name)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }

        public PageViewModel(Books.IPageFixed page) {
            this.Page = page;
        }

        private Books.IPageFixed Page;

        public float ZoomFactor
        {
            get
            {
                return this._ZoomFactor;
            }
            set
            {
                this._ZoomFactor = value;
                OnPropertyChanged(nameof(ZoomFactor));
            }
        }

        public void ZoomRequest(float factor)
        {
            OnZoomRequested(factor);
        }
        private void OnZoomRequested(float factor)
        {
            ZoomRequested?.Invoke(this, new ZoomRequestedEventArgs(factor));
        }
        public ZoomRequestedEventHandler ZoomRequested;
        public delegate void ZoomRequestedEventHandler(object sender, ZoomRequestedEventArgs e);
        public class ZoomRequestedEventArgs : EventArgs
        {
            public float ZoomFactor;
            public ZoomRequestedEventArgs(float factor)
            {
                this.ZoomFactor = factor;
            }
        }

        private float _ZoomFactor=1.0f;

        public ImageSource Source { get
            {
                if (_Source != null) return _Source;
                _Source = new BitmapImage();
                SetImageNoWait(_Source);
                //Page.Option.PropertyChanged += (s, e) => SetImageNoWait(_Source);
                return _Source;
            }
        }
        public BitmapImage _Source;

        public void UpdateSource()
        {
            SetImageNoWait(_Source);
        }

        private async void SetImageNoWait(BitmapImage im)
        {
            try {
                await Page.SetBitmapAsync(im);
            }
            catch
            {
                // ignored
            }
        }
    }

    public class Commands
    {
        public interface ICommandEventRaiseable : System.Windows.Input.ICommand
        {
            void OnCanExecuteChanged();
        }

        public class PageVisualAddCommand : ICommandEventRaiseable
        {
            public event EventHandler CanExecuteChanged;
            public void OnCanExecuteChanged() { if (CanExecuteChanged != null) CanExecuteChanged(this, new EventArgs()); }

            private BookViewModel model;

            public PageVisualAddCommand(BookViewModel model) { this.model = model; }

            public bool CanExecute(object parameter)
            {
                return model.PagesCount > model.PageSelectedVisual + int.Parse(parameter as string) && model.PageSelectedVisual >= -int.Parse(parameter as string);
            }

            public void Execute(object parameter)
            {
                model.PageSelectedVisual += int.Parse(parameter as string);
            }
        }

        public class PageVisualSetCommand : ICommandEventRaiseable
        {
            public event EventHandler CanExecuteChanged;
            public void OnCanExecuteChanged() { if (CanExecuteChanged != null) CanExecuteChanged(this, new EventArgs()); }

            private BookViewModel model;

            public PageVisualSetCommand(BookViewModel model) { this.model = model; }

            public bool CanExecute(object parameter)
            {
                return model.PagesCount > int.Parse(parameter as string) && 0 <= int.Parse(parameter as string) && model.PageSelectedVisual != int.Parse(parameter as string);
            }

            public void Execute(object parameter)
            {
                model.PageSelectedVisual = int.Parse(parameter as string);
            }
        }

        public class PageVisualMaxCommand : ICommandEventRaiseable
        {
            public event EventHandler CanExecuteChanged;
            public void OnCanExecuteChanged() { if (CanExecuteChanged != null) CanExecuteChanged(this, new EventArgs()); }

            private BookViewModel model;

            public PageVisualMaxCommand(BookViewModel model) { this.model = model; }

            public bool CanExecute(object parameter)
            {
                return model.PagesCount > 0 && model.PageSelectedVisual != model.PagesCount - 1;
            }

            public void Execute(object parameter)
            {
                model.PageSelectedVisual = model.PagesCount - 1;
            }
        }

        public class AddNumberToSelectedBook : System.Windows.Input.ICommand
        {
            public event EventHandler CanExecuteChanged;
            public void OnCanExecuteChanged() { if (CanExecuteChanged != null) CanExecuteChanged(this, new EventArgs()); }

            private BookViewModel ViewModel;
            private int NumberToAdd;

            public AddNumberToSelectedBook(BookViewModel vm, int i)
            {
                vm.PropertyChanged += (s, e) => { OnCanExecuteChanged(); };
                ViewModel = vm;
                NumberToAdd = i;
            }

            public bool CanExecute(object parameter)
            {
                return GetAddedBook(ViewModel.ID) != null;
            }

            public async void Execute(object parameter)
            {
                var bookFVM = GetAddedBook(ViewModel.ID);
                //var file = await bookFVM.TryGetBookFile();
                //var book = await Books.BookManager.GetBookFromFile(file);
                //if (book is Books.IBookFixed)
                //{
                //    ViewModel.Initialize(book as Books.IBookFixed);
                //    ViewModel.Title = System.IO.Path.GetFileNameWithoutExtension(file.Name);
                //    ViewModel.AsBookShelfBook = bookFVM;
                //}
            }

            public BookShelfViewModels.BookShelfBookViewModel GetAddedBook(string ID)
            {
                var books = ViewModel.AsBookShelfBook?.Parent?.Books;
                if (books == null) return null;
                //var book = books.Where(a => (a is BookShelfViewModels.BookViewModel && (a as BookShelfViewModels.BookViewModel).ID == ID)).First();
                var book = ViewModel.AsBookShelfBook;

                int cnt = 0;
                if (NumberToAdd == 0) return book as BookShelfViewModels.BookShelfBookViewModel;
                if (this.NumberToAdd > 0)
                {
                    for (int i = books.IndexOf(book) + 1; i < books.Count; i++)
                    {
                        if (books[i] is BookShelfViewModels.BookShelfBookViewModel) cnt++;
                        if (cnt == this.NumberToAdd) return books[i] as BookShelfViewModels.BookShelfBookViewModel;
                    }
                }
                else
                {
                    for (int i = books.IndexOf(book) - 1; i >= 0; i--)
                    {
                        if (books[i] is BookShelfViewModels.BookShelfBookViewModel) cnt--;
                        if (cnt == this.NumberToAdd) return books[i] as BookShelfViewModels.BookShelfBookViewModel;
                    }
                }
                return null;
            }
        }

        public class AddCurrentPageToBookmark : ICommandEventRaiseable
        {
            public event EventHandler CanExecuteChanged;
            public void OnCanExecuteChanged() { if (CanExecuteChanged != null) CanExecuteChanged(this, new EventArgs()); }

            private BookViewModel model;

            public AddCurrentPageToBookmark(BookViewModel model) { this.model = model; model.PropertyChanged += (s, e) => { if (e.PropertyName == nameof(model.PageSelectedDisplay)) { OnCanExecuteChanged(); } }; }

            public bool CanExecute(object parameter)
            {
                foreach(var bm in model.Bookmarks)
                {
                    if(bm.Page==model.PageSelectedDisplay && bm.AutoGenerated == false)
                    {
                        return false;
                    }
                }
                return true;
            }

            public void Execute(object parameter)
            {
                model.Bookmarks.Add(new BookmarkViewModel() { AutoGenerated = false, Page = model.PageSelectedDisplay, Title = parameter is string ? parameter as string : "" });
            }
        }

        public class CommandBase : ICommandEventRaiseable
        {
            public event EventHandler CanExecuteChanged;
            public void OnCanExecuteChanged() { if (CanExecuteChanged != null) CanExecuteChanged(this, new EventArgs()); }

            private Func<object, bool> CanExecuteFunc;
            private Action<object> ExecuteAction;

            public CommandBase(Func<object, bool> CanExecuteFunc, Action<object> ExecuteAction)
            {
                this.CanExecuteFunc = CanExecuteFunc;
                this.ExecuteAction = ExecuteAction;
            }

            public bool CanExecute(object parameter)
            {
                return CanExecuteFunc(parameter);
            }

            public void Execute(object parameter)
            {
                ExecuteAction(parameter);
            }
        }
    }

    public class BookmarkViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string name)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }

        public BookmarkViewModel() { }
        public BookmarkViewModel(BookInfoStorage.BookInfo.BookmarkItem item)
        {
            var rl = new Windows.ApplicationModel.Resources.ResourceLoader();
            this.Page = (int)item.Page;
            this.Title = string.IsNullOrEmpty(item.Title) ? item.Type == BookInfoStorage.BookInfo.BookmarkItem.BookmarkItemType.UserDefined ? rl.GetString("BookmarkBasic/Title") : rl.GetString("BookmarkLastread/Title") : item.Title;
            this.AutoGenerated = item.Type == BookInfoStorage.BookInfo.BookmarkItem.BookmarkItemType.LastRead;
        }

        public int Page
        {
            get { return _Page; }
            set { _Page = value; OnPropertyChanged(nameof(Page)); }
        }
        private int _Page;

        public string Title
        {
            get { return _Title; }
            set { _Title = value;OnPropertyChanged(nameof(Title)); }
        }
        private string _Title;

        public bool AutoGenerated { get { return _AutoGenerated; } set { _AutoGenerated = value;OnPropertyChanged(nameof(_AutoGenerated)); } }
        private bool _AutoGenerated;
    }
}
